# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

# 官方仓库CDN地址 pod 1.7.2
source 'https://cdn.cocoapods.org/'

target 'MyWorkBook' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # 忽略引入库的所有警告
  inhibit_all_warnings!
  
  pod 'SnapKit', '5.0.1'
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'
  
end
